### ISSUE TITLE
Converting onnx to nnet (for Neurify)

### ISSUE THREAD

**Issue by ChristopherBrix** [dlshriver/DNNV#10]
I am trying to convert the `mnist_0.1.onnx` network (from https://github.com/eth-sri/colt/tree/master/trained_models/onnx) to the `nnet` format used by Neurify.
When I run the analysis, this is the displayed network layout: 
```
Verifying Network:
Input_0                         : Input([ 1  1 28 28], dtype=float32)
Conv_0                          : Conv(Input_0)
Relu_0                          : Relu(Conv_0)
Conv_1                          : Conv(Relu_0)
Relu_1                          : Relu(Conv_1)
Shape_0                         : Shape(Relu_1)
Gather_0                        : Gather(Shape_0, 0, axis=0)
Unsqueeze_0                     : Unsqueeze(Gather_0, axes=[0])
Concat_0                        : Concat(['Unsqueeze_0', '[-1]'])
Reshape_0                       : Reshape(Relu_1, Concat_0)
Gemm_0                          : Gemm(Reshape_0, ndarray(shape=(100, 3136)), ndarray(shape=(100,)))
Relu_2                          : Relu(Gemm_0)
Gemm_1                          : Gemm(Relu_2, ndarray(shape=(10, 100)), ndarray(shape=(10,)))
```
So I guess there are 2 convolutional layers followed by 2 fully connected feed-forward layers with sizes 100 and 10.
However, the generated `nnet` file starts with
```
5,784,1,6272,
784,6272,3136,100,1,1,
1,1,0,0,0,
32,1,5,2,2,2
64,32,4,2,1,1
```
So apparently there are 3 FF layers with sizes 100, 1 and 1? This is a surprise to me, as a network with only one output node cannot solve MNIST.
I tried tracing this change to the network architecture through the program, and it might happen in https://github.com/dlshriver/DNNV/blob/239fcb53158e819e07ff297a545669508cf34f05/dnnv/verifiers/common/extractors.py#L284, but I'm not sure. While I try to figure this out, could you give me some pointers why you change the network layout and whether there's a simple way to avoid that, so I get exactly the model descriped in the onnx file?

**Comment by ChristopherBrix** [comment]
Ok, the mentioned function did indeed change the architecture. When I skip the last part https://github.com/dlshriver/DNNV/blob/239fcb53158e819e07ff297a545669508cf34f05/dnnv/verifiers/common/extractors.py#L298-L315 I get the original network structure.
However, I'm still not able to compute correct outputs. I've normalized the images from https://github.com/eth-sri/eran/blob/master/data/mnist_test.csv by dividing by 255, subtracted the mean 0.1307 and divided by the variance 0.3081. But the computed concrete output is eg. `4` for the first image (a 7). I've made sure to disable the explicit normalization by Neurify.
My best guess is that this is because of the way Neurify transforms the weights of the first FF layer after the convolution: https://github.com/tcwangshiqi-columbia/Neurify/blob/master/transfer.py#L43-L47 but I'm not sure how this needs to be applied to the weight matrix in the onnx file.

**Comment by dlshriver** [comment]
Sorry, I should make it more clear in the documentation that we use a generalized version of Neurify ([here](https://github.com/dlshriver/Neurify)) in order to support checking properties on networks other than MNIST, and that fixes several bugs in the original implementation. This general version of Neurify does not apply any pre-processing to inputs, and requires a single output value that is 0 when the property is violated, and positive otherwise. This is why extra fully connected layers are added, which convert the output constraints into layers which can compute this function. This version of Neurify also supports uneven padding.

**Comment by ChristopherBrix** [comment]
Oh, that's good to know! Thank you!
