### ISSUE TITLE
Difficulty installing BAB

### ISSUE THREAD

**Issue by AWbosman** [dlshriver/DNNV#103]
Dear Shriver, 

For a project I want to use DNNV, and specifically BaB. I follow your installation guide, namely creating a python3.7 env and then use pip to install dnnv. 
Everything goes right and I can install reluplex for instance without issues. When I try to install bab however, I get the error pasted bellow. 
It seems to be an issue with the dependency on the gurobi installer. 
Do you know how I can solve this? 

Thanks in advance!
A

> + cd /home/bosmanaw/NAS-NNV/.venv/verifier_virtualenvs
> + rm -rf bab
> + python -m venv bab
> Error: Command '['/home/bosmanaw/NAS-NNV/.venv/verifier_virtualenvs/bab/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
> Traceback (most recent call last):
>   File "/home/bosmanaw/NAS-NNV/.venv/bin/dnnv_manage", line 8, in <module>
>     sys.exit(_main())
>   File "/home/bosmanaw/NAS-NNV/.venv/lib/python3.7/site-packages/dnnv/_manage/__main__.py", line 95, in _main
>     return args.command(**params)
>   File "/home/bosmanaw/NAS-NNV/.venv/lib/python3.7/site-packages/dnnv/_manage/linux/__init__.py", line 18, in install
>     import_verifier_module(verifier).install(environment)
>   File "/home/bosmanaw/NAS-NNV/.venv/lib/python3.7/site-packages/dnnv/_manage/linux/verifiers/bab.py", line 163, in install
>     ProgramDependency("grbgetkey", installer=gurobi_installer),
>   File "/home/bosmanaw/NAS-NNV/.venv/lib/python3.7/site-packages/dnnv/_manage/linux/environment/base.py", line 94, in ensure_dependencies
>     self.ensure_dependency(dependency)
>   File "/home/bosmanaw/NAS-NNV/.venv/lib/python3.7/site-packages/dnnv/_manage/linux/environment/base.py", line 87, in ensure_dependency
>     dependency.install(self)
>   File "/home/bosmanaw/NAS-NNV/.venv/lib/python3.7/site-packages/dnnv/_manage/linux/environment/dependencies/base.py", line 39, in install
>     self.installer.run(env, self)
>   File "/home/bosmanaw/NAS-NNV/.venv/lib/python3.7/site-packages/dnnv/_manage/linux/verifiers/bab.py", line 137, in run
>     raise InstallError("Installation of bab failed")
> dnnv._manage.errors.InstallError: Installation of bab failed

**Comment by dlshriver** [comment]
How did you create the virtual environment? When installing a verifier, we create new verifier specific environments, but that seems to fail here due to the absence of `ensurepip`. I'm surprised that this is missing, since I assumed it is required to build the virtual environment in which you installed dnnv, so could you describe the steps you took to create the environment and install dnnv?

**Comment by AWbosman** [comment]
I tried two ways.
Using my alias:
python3.7-env='python3.7 -m venv .venv && source .venv/bin/activate && pip install --upgrade pip && pip install --upgrade setuptools wheel'

And using your installation guide:

python3.7 -m venv .venv
. .venv/bin/activate
pip install --upgrade pip flit
flit install -s

It did give an error saying it did not recognise -s in flit install.

**Comment by dlshriver** [comment]
Very interesting. The `flit` error suggests to me that it doesn't like something about the environment. Maybe using `python3 -m pip ...` instead of just `pip` could fix it?

Could you send some more information about your system? OS, python version, and maybe how you installed python? And the output of `python -c "import sys;print(sys.version)"`?

**Comment by AWbosman** [comment]
Weirdly enough, I upgraded ensurepip after creating a new enivironment and the issue went away. I say weirdly, because the output said all requirements were met, yet when I make a new environment the same error occurs. 

Anyway, thank you for your help! Its very much appreciated.
