### ISSUE TITLE
the root password of the official docker

### ISSUE THREAD

**Issue by urays** [dlshriver/DNNV#110]
Hello,
when I install other useful tools on the formal Docker, the system prompts me to install them in the root environment.
So, I would like to ask if it is possible to provide the password of the official docker's super user?

thanks in advance.

**Comment by dlshriver** [comment]
I don't believe there is a root password. It's not designed to enable root access, just to provide access to DNNV. One option is to use the `--user root` option when starting your container to login as root instead (which shouldn't require a password). However, if you are trying to build a new image with additional system dependencies, this should generally be done with a Dockerfile.

**Comment by urays** [comment]
:) got it, thank you.
