### ISSUE TITLE
Custom NN verification

### ISSUE THREAD

**Issue by preritt** [dlshriver/DNNV#19]
Hi
Can I use my own network for verification. More specifically, I'd like to verify fully connected network trained using mean-squared error. Consider a network with 3 inputs and 2 outputs - can the following code be used for verification? I am not sure how should the inputs x_ be specified.

```
from dnnv.properties import *
import numpy as np
import os


N = Network("N") # pre-trained fully connected network  (3 inputs and 2 outputs) converted to acceptable format (onxx). Name of the saved network is N


Forall(
    x_,
    Implies(
        0 <= x_[0] <= 1,
         0 <= x_[1] <= 1.5,
          0 <= x_[2] <= 5,
        And(
            Implies(N(x_)[0, 0] > .5)
            Implies(N(x_)[0, 1] < .3)
        ),
    ),
)
```

Thanks

**Comment by dlshriver** [comment]
Yes, you can use your own networks.
The specification will depend on the input and output shape of the network. If the network expects input tensors with 2 axes, a batch axis and a feature axis, then the indices used for specifying lower and upper bounds will require 2 values (e.g., `0 <= x_[0, 2] <= 5`).

**Comment by dlshriver** [comment]
For the example property specified in your post, I believe it should look something like the following if the inputs have 2 axes:

```
from dnnv.properties import *

N = Network("N") # pre-trained fully connected network  (3 inputs and 2 outputs) converted to acceptable format (onxx). Name of the saved network is N

Forall(
    x_,
    Implies(
        And(0 <= x_[0, 0] <= 1,
            0 <= x_[0, 1] <= 1.5,
            0 <= x_[0, 2] <= 5),
        And(
            N(x_)[0, 0] > .5,
            N(x_)[0, 1] < .3
        ),
    ),
)
```

`Implies` takes 2 arguments: an antecedent and a consequent. The property above specifies that for all inputs where the first feature has a value between 0 and 1, the second feature has a value between 0 and 1.5, and the third feature has a value between 0 and 5, then the first output value will be greater than 0.5 and the second output value will be less than 0.3.

**Comment by preritt** [comment]
Hi
Thanks for your response.
 I tried running a sample examples below and got `unsat` which is likely expected. However, in general case, considering the example posted above - if the network meets the specified property, how do I get the corresponding inputs that meets the requirements?  For the example above, what should be done to see the three inputs `x_[0, 0], x_[0, 1], x_[0, 2]` to the network that meets the requirement?

```
python -m dnnv --eran onnx/pyt/ffnnRELU__Point_6_500.onnx properties/property_7.py
Verifying Network:
Input_0                         : Input([ 1  1 28 28], dtype=float32)
Conv_0                          : Conv(Input_0)
Transpose_0                     : Transpose(Conv_0, permutation=[0 2 3 1])
Reshape_0                       : Reshape(Transpose_0, [ -1 784])
Gemm_0                          : Gemm(Reshape_0, ndarray(shape=(500, 784)), ndarray(shape=(500,)))
Relu_0                          : Relu(Gemm_0)
Gemm_1                          : Gemm(Relu_0, ndarray(shape=(500, 500)), ndarray(shape=(500,)))
Relu_1                          : Relu(Gemm_1)
Gemm_2                          : Gemm(Relu_1, ndarray(shape=(500, 500)), ndarray(shape=(500,)))
Relu_2                          : Relu(Gemm_2)
Gemm_3                          : Gemm(Relu_2, ndarray(shape=(500, 500)), ndarray(shape=(500,)))
Relu_3                          : Relu(Gemm_3)
Gemm_4                          : Gemm(Relu_3, ndarray(shape=(500, 500)), ndarray(shape=(500,)))
Relu_4                          : Relu(Gemm_4)
Gemm_5                          : Gemm(Relu_4, ndarray(shape=(500, 500)), ndarray(shape=(500,)))
Relu_5                          : Relu(Gemm_5)
Gemm_6                          : Gemm(Relu_5, ndarray(shape=(10, 500)), ndarray(shape=(10,)))

Verifying property:
Forall(x_0, (((([[[[0. 0. ... 0. 0.]  [0. 0. ... 0. 0.]  ...  [0. 0. ... 0. 0.]  [0. 0. ... 0. 0.]]]] - 0.00784313725490196) < x_0) & (x_0 < 1) & (0 < x_0) & (x_0 < ([[[[0. 0. ... 0. 0.]  [0. 0. ... 0. 0.]  ...  [0. 0. ... 0. 0.]  [0. 0. ... 0. 0.]]]] + 0.00784313725490196))) ==> (numpy.argmax(N(x_0)) == 9)))
This network has 3001 neurons.
This network has 3001 neurons.
This network has 3001 neurons.
This network has 3001 neurons.
This network has 3001 neurons.
This network has 3001 neurons.
This network has 3001 neurons.
This network has 3001 neurons.
This network has 3001 neurons.
dnnv.verifiers.eran
  result: unsat
  time: 22.5618
```

**Comment by dlshriver** [comment]
A result of `unsat` indicates that the property holds, and no violation was found. If the result is `unsat` then all inputs satisfy the property. There are no violations. You can pick any input in your specified input region and it satisfies your requirement. If the result is `sat`, it indicates that a violation was found. In this case, there is not currently any way to see a violating input.

**Comment by preritt** [comment]
Thanks, I was interested in looking at the output when the result is `sat`. Any plans to add this functionality in the future?

**Comment by dlshriver** [comment]
There's not a plan to add this feature at the moment, but I agree it could be useful and it should be added in the future so I'll keep it in mind and try to add it before version 1.0 is released.

**Comment by preritt** [comment]
Great, thanks for letting me know.
