### ISSUE TITLE
Outdated dependencies in pip. 

### ISSUE THREAD

**Issue by pat676** [dlshriver/DNNV#45]
The current pip version of dnnv seems to have stricter requirements than the requirements file in the repo (e.g. numpy==1.16.4 and onnx==1.6).

Especially the NumPy requirement from pip conflict with some other libraries, would it be possible to update this? 

Thanks!

**Comment by dlshriver** [comment]
I'm not sure where the `numpy==1.16.4` and `onnx==1.6` examples are from, could you clarify? The numpy requirement for DNNV is currently any version greater than or equal to 1.18 and less than 1.20, and the onnx requirement is any version greater than or equal to 1.7 and less than 1.8. Are you asking for older versions of these packages to be allowed or newer?

**Comment by pat676** [comment]
Running "pipenv install dnnv" (this should install the same version of dnnv as "pip install dnnv") gives the following output:
`
numpy==1.16.4 (from dnnv==0.2.1->-r /var/folders/j5/gbqc_s712x38mm72ysv6hb5h0000gn/T/pipenvb2ohr1bbrequirements/pipenv-v79frlur-constraints.txt (line 11))
`

It seems like pip is trying to install an older version of dnnv (0.2.1), which explains the old numpy dependency. I'm trying to install the current version of dnnv via pip.

**Comment by dlshriver** [comment]
It doesn't look like pipenv is installing the latest version of DNNV. The latest version is 0.4.6 ([on pypi](https://pypi.org/project/dnnv/)). I'm not very familiar with pipenv but `pipenv install dnnv==0.4.6` might force it to install that version. 

You may also be on an older version of python. I think DNNV version 0.2, supported python3.6, but from version 0.3 on we require at least python3.7. This may be why pipenv is selecting an older version of DNNV.

**Comment by pat676** [comment]
Thanks! I'm using Python 3.6 so that may be it, I'll test a newer version of Python and see if it works.
