### ISSUE TITLE
Problem with some onnx networks

### ISSUE THREAD

**Issue by sergedurand** [dlshriver/DNNV#48]
DNNV fails on ACAS network produced by the converters here: https://github.com/sisl/NNet/tree/master/converters (so for example all the onnx provided on the eran repo).
The error is 
```
 python -m dnnv --nnenum --network N ACAS_Xu/ACASXU_run2a_1_1_batch_2000.onnx ACAS_Xu/properties/property_3.py 
Verifying property:
Forall(x0, ((([[-0.304 -0.01  0.493 0.3  0.3 ]] <= x0) & (x0 <= [[-0.299 0.01  0.5  0.5  0.5 ]])) ==> (numpy.argmin(N(x0)) != 0)))

Verifying Networks:
N:
2021-06-17 16:38:55.282727: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
Input_0                         : Input([5], dtype=float32)
MatMul_0                        : MatMul(Input_0, ndarray(shape=(5, 50)))
Add_0                           : Add(MatMul_0, ndarray(shape=(50,)))
Relu_0                          : Relu(Add_0)
MatMul_1                        : MatMul(Relu_0, ndarray(shape=(50, 50)))
Add_1                           : Add(MatMul_1, ndarray(shape=(50,)))
Relu_1                          : Relu(Add_1)
MatMul_2                        : MatMul(Relu_1, ndarray(shape=(50, 50)))
Add_2                           : Add(MatMul_2, ndarray(shape=(50,)))
Relu_2                          : Relu(Add_2)
MatMul_3                        : MatMul(Relu_2, ndarray(shape=(50, 50)))
Add_3                           : Add(MatMul_3, ndarray(shape=(50,)))
Relu_3                          : Relu(Add_3)
MatMul_4                        : MatMul(Relu_3, ndarray(shape=(50, 50)))
Add_4                           : Add(MatMul_4, ndarray(shape=(50,)))
Relu_4                          : Relu(Add_4)
MatMul_5                        : MatMul(Relu_4, ndarray(shape=(50, 50)))
Add_5                           : Add(MatMul_5, ndarray(shape=(50,)))
Relu_5                          : Relu(Add_5)
MatMul_6                        : MatMul(Relu_5, ndarray(shape=(50, 5)))
Add_6                           : Add(MatMul_6, ndarray(shape=(5,)))

dnnv.verifiers.nnenum
  result: NnenumTranslatorError(Invalid property: Comparing expressions with different shapes is not supported
```

rhs shape is (1, 5) while c_shape is (5,) (I suggest printing the shapes when raising the error to help debug). The problem arise with any verifier, as far as I tested.

I realize a quick work-around is to use the provided converter in DNNV (reluplexnnet2onnx) but I think those type of network could be supported out of the box by DNNV. 

I'm attaching the netron display of the networks to see more clearly the difference (use of matmul + add instead of gemm and input and output shape are 1D instead of 2D). 
Failing onnx:
![failing_onnx](https://user-images.githubusercontent.com/46579305/122420806-3bc3f080-cf8c-11eb-9dde-bfff0e234df4.png)
Working onnx:
![working_onnx](https://user-images.githubusercontent.com/46579305/122420827-3f577780-cf8c-11eb-8286-90267856816f.png)

**Comment by dlshriver** [comment]
DNNV does support these networks. This error is caused by the property specification being written for a network with a different input shape than the one provided. The property specification bounds the inputs between tensors with shape (1, 5), but the shape of the input inferred by DNNV from the network is (5,). Modifying the property so that the upper and lower bounds for x have shape (5,) will fix the problem. The following should work:

```
"""
Property $\phi_3$.
  – Description: If the intruder is directly ahead and is moving towards the ownship, the score for COC will not be minimal.
  – Tested on: all networks except $N_{1,7}$, $N_{1,8}$, and $N_{1,9}$.
  – Input constraints: $1500 \le \rho \le 1800$, $−0.06 \le \theta \le 0.06$, $\psi \ge 3.10$, $v_{own} \ge 980$, $v_{int} \ge 960$.
  – Desired output property: the score for COC is not the minimal score.
"""
from dnnv.properties import *
import numpy as np

N = Network("N")
# x: $\rho$, $\theta$, $\psi$, $v_{own}$, $v_{int}$
# x_{min}: 0.0, -3.141593, -3.141593, 100.0, 0.0
# x_{max}: 60760.0, 3.141593, 3.141593, 1200.0, 1200.0
x_min = np.array([1500.0, -0.06, 3.10, 980.0, 960.0])
x_max = np.array([1800.0, 0.06, 3.141593, 1200.0, 1200.0])

x_mean = np.array([1.9791091e04, 0.0, 0.0, 650.0, 600.0])
x_range = np.array([60261.0, 6.28318530718, 6.28318530718, 1100.0, 1200.0])

x_min_normalized = (x_min - x_mean) / x_range
x_max_normalized = (x_max - x_mean) / x_range

# y: Clear-of-Conflict, weak left, weak right, strong left, strong right
y_mean = 7.5188840201005975
y_range = 373.94992

Forall(
    x, Implies(x_min_normalized <= x <= x_max_normalized, np.argmin(N(x)) != 0),
)
```

I do agree the error message here is not very clear. This discrepancy between the property specification and the network is caught during property reduction, which is independent of the network. I can look into trying to identify ways to provide better error messages here to help with debugging specifications/networks.

**Comment by sergedurand** [comment]
Thanks! I didn't think of adapting the property specification, indeed it works with the reshaped arrays.
