### ISSUE TITLE
MIPverify result error

### ISSUE THREAD

**Issue by GuantingPan** [dlshriver/DNNV#53]
Hi David,

I was trying to run the MIPverify with some example, and I got this error

```
(.venv) guanting@guanting-ThinkPad:~/Desktop/DNNV$ python -m dnnv vnncomp2021/benchmarks/acasxu/prop_1.vnnlib --network N vnncomp2021/benchmarks/acasxu/ACASXU_run2a_1_1_batch_2000.onnx --mipverify --vnnlib
Verifying property:
Forall(X, ((X[numpy.unravel_index(4, N.input_shape[0])] < -0.5) | (X[numpy.unravel_index(0, N.input_shape[0])] > 0.679857769) | (X[numpy.unravel_index(3, N.input_shape[0])] > 0.5) | (X[numpy.unravel_index(4, N.input_shape[0])] > -0.45) | (X[numpy.unravel_index(3, N.input_shape[0])] < 0.45) | (X[numpy.unravel_index(1, N.input_shape[0])] < -0.5) | (X[numpy.unravel_index(2, N.input_shape[0])] < -0.5) | (X[numpy.unravel_index(1, N.input_shape[0])] > 0.5) | (X[numpy.unravel_index(2, N.input_shape[0])] > 0.5) | (X[numpy.unravel_index(0, N.input_shape[0])] < 0.6) | (N(X)[numpy.unravel_index(0, N.output_shape[0])] < 3.991125645861615)))

Verifying Networks:
N:
2021-07-01 23:03:02.278592: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
Input_0                         : Input([1 1 1 5], dtype=float32)
Flatten_0                       : Flatten(Input_0, axis=1)
Gemm_0                          : Gemm(Flatten_0, ndarray(shape=(5, 50)), ndarray(shape=(50,)))
Relu_0                          : Relu(Gemm_0)
Gemm_1                          : Gemm(Relu_0, ndarray(shape=(50, 50)), ndarray(shape=(50,)))
Relu_1                          : Relu(Gemm_1)
Gemm_2                          : Gemm(Relu_1, ndarray(shape=(50, 50)), ndarray(shape=(50,)))
Relu_2                          : Relu(Gemm_2)
Gemm_3                          : Gemm(Relu_2, ndarray(shape=(50, 50)), ndarray(shape=(50,)))
Relu_3                          : Relu(Gemm_3)
Gemm_4                          : Gemm(Relu_3, ndarray(shape=(50, 50)), ndarray(shape=(50,)))
Relu_4                          : Relu(Gemm_4)
Gemm_5                          : Gemm(Relu_4, ndarray(shape=(50, 50)), ndarray(shape=(50,)))
Relu_5                          : Relu(Gemm_5)
Gemm_6                          : Gemm(Relu_5, ndarray(shape=(50, 5)), ndarray(shape=(5,)))

dnnv.verifiers.mipverify
  result: MIPVerifyTranslatorError(Multiple epsilon values are not supported)
  time: 0.6442
```
Is this an format error? 

And may I have another question? Since MIPverify is evaluating the robustness of NN using MIP and the input here is in onnx file, is the onnx file be converted to a MIP problem in the MIPverify tool? Or the onnx is converted in other place in this DNNV package? 

Thank you so much for your time.

**Comment by dlshriver** [comment]
MIPVerify requires input constraints to be a hypercube (i.e., the size of the interval must be the same for each input dimension), however this property doesn't satisfy that requirement. Each input dimension has a different size of interval. DNNV should be able to support this if the network didn't use input tensors with 4 axes (like the ones we provide [here](http://cs.virginia.edu/~dls2fc/acasxu_benchmark.tar.gz)). When the input tensor is already flat, then DNNV should be able to modify the network and property to make this work. The 4 dimensional input followed by a flatten is throwing it off here, I'll see if we can work around that.

For the translation to the input formats of MIPVerify, we use their [Julia API](https://vtjeng.com/MIPVerify.jl/latest/). We convert both the network and property to forms that can be loaded into Julia and solved with MIPVerify.

**Comment by GuantingPan** [comment]
Thank you so much for your answer!
