### ISSUE TITLE
ACAS-XU 

### ISSUE THREAD

**Issue by khedher1984** [dlshriver/DNNV#60]
Hello,
can we use nnet models for ACS-XU ?
Thank you.

**Comment by dlshriver** [comment]
We do not support the nnet format. The ACAS Xu models are available in ONNX format [here](http://cs.virginia.edu/~dls2fc/acasxu_benchmark.tar.gz), and we provide a tool for converting other nnet models (in the reluplex nnet dialect) to ONNX in `tools/reluplexnnet2onnx.py`.

**Comment by khedher1984** [comment]
Thank you for your answer.
I would like to ask you another question.
The docker version does not support the --mipverify option. Could you confirm ? Do you have a new docker image?

**Comment by dlshriver** [comment]
MIPVerify relies on the Gurobi LP solver, which does not work in a docker container. Several verifiers rely on this solver (BaB, Verinet, MIPVerify) and so they are not included in the pre-built docker image.

**Comment by khedher1984** [comment]
Thank you for your help.
I tried to use marabou on local not in docker. And I get the folowing output
![image](https://user-images.githubusercontent.com/34816981/133114126-fe151597-4ddc-4f6f-8bb8-0d312522f210.png)
46 / 5000
Résultats de traduction
What does Marabou error mean? Can you help me?

**Comment by dlshriver** [comment]
MarabouError means something went wrong when trying to run the Marabou verifier. The return code is just the exit code of the verifier process. Return code 1 often means that the verifier is not installed correctly. Running with `--debug` will provide some more error information. I would suggest trying to re-install the verifier.
