### ISSUE TITLE
run file for ACAS-XU

### ISSUE THREAD

**Issue by khedher1984** [dlshriver/DNNV#61]
Hello,
I need to run the script  for all experiences on ACAS-XU ? 
How can I specify the verifier ?
Which command should be launched ? 

Thank you.

**Comment by dlshriver** [comment]
What script do you mean? DNNV is benchmark agnostic. It does not include any benchmarks or make any assumptions about what benchmark is being run. 

I have made the ACAS Xu benchmark available [here](http://cs.virginia.edu/~dls2fc/acasxu_benchmark.tar.gz), separate from DNNV. I believe all of the properties can be run by using the script `run.sh` included in that archive, but I have not tested it recently. It believe it runs most of the verifiers. You can modify the run script to choose a specific verifier to run. There is also a version of the ACAS Xu benchmark (specified in VNNLIB) in [this repo](https://github.com/stanleybak/vnncomp2021), in `benchmarks/acasxu`, but I don't think they provide a run script for DNNV, although they do provide a CSV file with the combinations of property and network combinations which you could parse.
