### ISSUE TITLE
using "pip install dnnv"

### ISSUE THREAD

**Issue by GuantingPan** [dlshriver/DNNV#65]
Hi,

Thank you so much for reading this! 

Do you recommend installing dnnv by using "pip install dnnv" without activating virtual environment? I believe we need to install the verifiers separately, which also must be accessible on the PATH. But I am not very sure how to install the verifiers separately after I use "pip install dnnv". May I get some help with this? (Like what command line should I use.)

Thank you so much for your time!

**Comment by dlshriver** [comment]
No, if you need to use verifiers, then I would not recommend installation with pip. The pip version is useful if you just need the network simplification and property reduction methods, but it is much harder to use the verifiers (it is probably possible but won't be officially supported).

**Comment by GuantingPan** [comment]
Thank you so much for the answer!
